# Generated by Django 4.0.4 on 2022-06-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
