# Generated by Django 4.0.4 on 2022-06-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
